services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - SETTINGS_ENCRYPTION_KEY=
      - DUPLICATI__WEBSERVICE_PASSWORD=
    volumes:
      - /vol3/1000/Docker/duplicati:/config
      - /vol1/1000:/source1
      - /vol2/1000:/source2
    ports:
      - 8200:8200
    restart: always
