services:
  lxmusicsyncserver:
    image: woodchen/lxmusicsyncserver
    container_name: lxmusicsyncserver
    restart: always
    ports:
      - "19527:9527"
    volumes:
      - /vol3/1000/Docker/lxmusic/logs:/server/logs
      - /vol3/1000/Docker/lxmusic/data:/server/data
    environment:
      - TZ=Asia/Shanghai
      - LX_USER_wood1=wood1
      - LX_USER_wood=wood
      - BIND_IP=0.0.0.0
      - PORT=9527    
