services:
  lxmusicsyncserver:
    image: woodchen/lxmusicsyncserver
    container_name: lxmusicsyncserver
    restart: always
    ports:
      - "19527:9527"
    volumes:
      - /vol3/1000/Docker/lxmusic/logs:/server/logs
      - /vol3/1000/Docker/lxmusic/data:/server/data
    environment:
      - TZ=Asia/Shanghai
      - LX_USER_wood1=wood1
      - LX_USER_wood=wood
      - BIND_IP=0.0.0.0
      - PORT=9527    
      - LX_USER_user1=密码

# 使用方法参考
# https://laosu.cf/2023/03/31/%E6%B4%9B%E9%9B%AA%E9%9F%B3%E4%B9%90%E5%8A%A9%E6%89%8B%E5%90%8C%E6%AD%A5%E6%9C%8D%E5%8A%A1%E7%9A%84%E6%90%AD%E5%BB%BA/?highlight=lx

