services:
    v2raya:
        image: ghcr.nju.edu.cn/sqing33/v2raya
        volumes:
            - '/vol1/1000/Docker/v2raya/data:/etc/v2raya'
            - '/vol1/1000/Docker/v2raya/modules:/lib/modules:ro'
        environment:
            - IPTABLES_MODE=legacy
            - V2RAYA_NFTABLES_SUPPORT=off
            - V2RAYA_V2RAY_BIN=/usr/local/bin/v2ray
            - V2RAYA_LOG_FILE=/tmp/v2raya.log
        container_name: v2raya
        ports:
            - 2017:2017
            - 20172:20172
        privileged: true
        restart: always
